// ============================================================
// FluxionJS V3 — Physics Geometry Bridge
// FFI layer between PhysicsBodySystem and the
// fluxion-core Wasm extract_geometry_wasm export.
//
// Input/Output protocol matches fluxion-core/src/physics/geometry.rs.
// ============================================================

import * as THREE from 'three';

// ── Wasm module slot ──────────────────────────────────────────────────────────

interface WasmPhysicsModule {
  extract_geometry_wasm(input: Float32Array): Float32Array;
}

let _wasm: WasmPhysicsModule | null = null;
let _wasmLoading: Promise<void> | null = null;

/** Load the fluxion-core Wasm module for physics geometry use. Safe to call multiple times. */
export async function initPhysicsGeometryCore(): Promise<void> {
  if (_wasm) return;
  if (_wasmLoading) return _wasmLoading;

  _wasmLoading = (async () => {
    try {
      // @ts-ignore — generated by wasm-pack
      const mod = await import(/* webpackChunkName: "fluxion-core" */ '../../fluxion-core/pkg/fluxion_core.js') as any;
      if (mod.default) await mod.default();
      _wasm = mod as WasmPhysicsModule;
      console.info('[PhysicsGeometryBridge] fluxion-core Wasm loaded — using native geometry extraction.');
    } catch {
      throw new Error('[PhysicsGeometryBridge] fluxion-core Wasm unavailable — physics geometry extraction requires Wasm.');
    }
    _wasmLoading = null;
  })();

  return _wasmLoading;
}

export function isPhysicsGeometryNativeAvailable(): boolean {
  return _wasm !== null;
}

// ── Output layout constants (must match fluxion-core/src/physics/geometry.rs) ─

const OUT_TOTAL_VERTS = 0;
const OUT_TOTAL_IDXS  = 1;
const OUT_DATA_START  = 2;

// ── Input packing constants ───────────────────────────────────────────────────

const SCALE_HEADER = 4;  // apply_scale, sx, sy, sz
const BLOCK_HEADER = 4;  // vertex_count, index_count, pad, pad
const MATRIX_SIZE  = 16; // column-major Mat4

// ── Public types ──────────────────────────────────────────────────────────────

export interface MeshGeo {
  vertices: Float32Array;
  indices:  Uint32Array;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Extract and merge geometry from a THREE.Object3D tree using the Rust Wasm backend.
 * Applies each mesh's world matrix and optionally the entity's world scale.
 *
 * Throws if the Wasm module is not loaded — call initPhysicsGeometryCore() first.
 */
export function extractGeometryNative(
  root:       THREE.Object3D,
  worldScale: THREE.Vector3 | null = null,
): MeshGeo | null {
  if (!_wasm) {
    throw new Error('[PhysicsGeometryBridge] Wasm not loaded. Call initPhysicsGeometryCore() before use.');
  }

  // ── Collect meshes from the scene tree ─────────────────────────────────────
  const meshes: THREE.Mesh[] = [];
  root.traverse((obj) => {
    if (obj instanceof THREE.Mesh && (obj as THREE.Mesh).geometry) {
      meshes.push(obj as THREE.Mesh);
    }
  });

  if (meshes.length === 0) return null;

  // ── Compute total buffer size ──────────────────────────────────────────────
  let totalFloats = SCALE_HEADER;
  for (const mesh of meshes) {
    const geo      = mesh.geometry as THREE.BufferGeometry;
    const posAttr  = geo.getAttribute('position') as THREE.BufferAttribute | undefined;
    if (!posAttr) continue;
    const vCount   = posAttr.count;
    const iCount   = geo.index ? geo.index.count : 0;
    totalFloats   += BLOCK_HEADER + MATRIX_SIZE + vCount * 3 + iCount;
  }

  // ── Pack input buffer ──────────────────────────────────────────────────────
  const applyScale =
    worldScale !== null &&
    (worldScale.x !== 1 || worldScale.y !== 1 || worldScale.z !== 1);

  const input = new Float32Array(totalFloats);
  input[0] = applyScale ? 1.0 : 0.0;
  input[1] = worldScale ? worldScale.x : 1.0;
  input[2] = worldScale ? worldScale.y : 1.0;
  input[3] = worldScale ? worldScale.z : 1.0;

  let offset = SCALE_HEADER;

  for (const mesh of meshes) {
    const geo     = mesh.geometry as THREE.BufferGeometry;
    const posAttr = geo.getAttribute('position') as THREE.BufferAttribute | undefined;
    if (!posAttr) continue;

    const vCount = posAttr.count;
    const iCount = geo.index ? geo.index.count : 0;

    // Block header
    input[offset    ] = vCount;
    input[offset + 1] = iCount;
    input[offset + 2] = 0;
    input[offset + 3] = 0;
    offset += BLOCK_HEADER;

    // World matrix (column-major, directly from THREE.js matrixWorld.elements)
    const elems = mesh.matrixWorld.elements;
    for (let i = 0; i < 16; i++) {
      input[offset + i] = elems[i];
    }
    offset += MATRIX_SIZE;

    // Vertices (local space — Rust applies the world matrix)
    for (let i = 0; i < vCount; i++) {
      input[offset + i * 3    ] = posAttr.getX(i);
      input[offset + i * 3 + 1] = posAttr.getY(i);
      input[offset + i * 3 + 2] = posAttr.getZ(i);
    }
    offset += vCount * 3;

    // Indices
    if (geo.index && iCount > 0) {
      for (let i = 0; i < iCount; i++) {
        input[offset + i] = geo.index.array[i];
      }
      offset += iCount;
    }
  }

  // ── Call Wasm ─────────────────────────────────────────────────────────────
  const output = _wasm.extract_geometry_wasm(input);

  const totalVerts = output[OUT_TOTAL_VERTS] as number;
  const totalIdxs  = output[OUT_TOTAL_IDXS]  as number;

  if (totalVerts === 0) return null;

  const vertsStart = OUT_DATA_START;
  const idxsStart  = vertsStart + totalVerts * 3;

  const vertices = new Float32Array(output.buffer, output.byteOffset + vertsStart * 4, totalVerts * 3);
  const idxsRaw  = new Float32Array(output.buffer, output.byteOffset + idxsStart  * 4, totalIdxs);
  const indices  = new Uint32Array(totalIdxs);
  for (let i = 0; i < totalIdxs; i++) {
    indices[i] = idxsRaw[i];
  }

  return {
    vertices: new Float32Array(vertices), // copy — Wasm memory may be invalidated
    indices,
  };
}
