// FluxionJS V2 — Icon definitions
export const Icons = {
  cube: '▣',
  light: '☀',
  camera: '📷',
  physics: '⊛',
  particle: '✦',
  entity: '◆',
  folder: '📁',
  file: '📄',
  scene: '🎬',
  material: '🎨',
  audio: '🔊',
  script: '📜',
  play: '▶',
  pause: '⏸',
  stop: '⏹',
  select: '◇',
  move: '✥',
  rotate: '↻',
  scale: '⤢',
  plus: '+',
  minus: '−',
  close: '✕',
  minimize: '─',
  maximize: '□',
  chevronDown: '▼',
  chevronRight: '▶',
  search: '🔍',
  settings: '⚙',
  grid: '⊞',
  localSpace: 'L',
  worldSpace: 'W',
} as const;
