// ============================================================
// FluxionJS V3 — CSG ↔ THREE.js Bridge
// Converts CSG polygons to THREE.BufferGeometry and back.
// Fast path: Rust/Wasm (fluxion-core) when available.
// Fallback:  pure-JS BSP (CSGCore.ts).
// ============================================================

import * as THREE from 'three';
import { CSG, CSGVertex, CSGPolygon, Vec3, Vec2 } from './CSGCore';

// ── Flat-array mesh representation (mirrors fluxion_core::csg::bridge::CsgMeshData) ──

export interface CsgMeshData {
  positions:    number[];
  normals:      number[];
  uvs:          number[];
  vertexCounts: number[];
  shared:       number[];
}

// ── Wasm module slot ───────────────────────────────────────────────────────────

/** Loaded fluxion-core Wasm module (browser). Null until initCsgCore() is called. */
let _wasmCsg: { csg_op: (a: string, b: string, op: string) => string; csg_op_batch: (base: string, ops: string) => string } | null = null;
let _wasmLoading: Promise<void> | null = null;

/** Load the fluxion-core Wasm module for browser use. Safe to call multiple times. */
export async function initCsgCore(): Promise<void> {
  if (_wasmCsg) return;
  if (_wasmLoading) return _wasmLoading;

  _wasmLoading = (async () => {
    try {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore — generated by wasm-pack, does not exist until `npm run build:wasm-csg` is run
      const mod = await import(/* webpackChunkName: "fluxion-core-csg" */ '../../fluxion-core/pkg/fluxion_core.js') as any;
      if (mod.default) await mod.default();
      _wasmCsg = mod;
      console.info('[CSGBridge] fluxion-core Wasm loaded — using native CSG.');
    } catch {
      console.info('[CSGBridge] fluxion-core Wasm unavailable — using JS fallback.');
    }
    _wasmLoading = null;
  })();

  return _wasmLoading;
}

/** True when the native Rust/Wasm CSG path is available. */
export function isCsgNativeAvailable(): boolean {
  return _wasmCsg !== null || typeof (window as any).__TAURI__ !== 'undefined';
}

// ── CSG ↔ flat-array converters ───────────────────────────────────────────────

/** Convert a CSG solid to the serializable flat-array format. */
export function csgToMeshData(csg: CSG): CsgMeshData {
  const positions:    number[] = [];
  const normals:      number[] = [];
  const uvs:          number[] = [];
  const vertexCounts: number[] = [];
  const shared:       number[] = [];

  for (const poly of csg.polygons) {
    vertexCounts.push(poly.vertices.length);
    shared.push(poly.shared);
    for (const v of poly.vertices) {
      positions.push(v.pos.x, v.pos.y, v.pos.z);
      normals.push(v.normal.x, v.normal.y, v.normal.z);
      uvs.push(v.uv.x, v.uv.y);
    }
  }

  return { positions, normals, uvs, vertexCounts, shared };
}

/** Reconstruct a CSG solid from the flat-array format. */
export function meshDataToCSG(data: CsgMeshData): CSG {
  const polys: CSGPolygon[] = [];
  let offset = 0;

  for (let pi = 0; pi < data.vertexCounts.length; pi++) {
    const vc   = data.vertexCounts[pi];
    const sh   = data.shared[pi] ?? 0;
    const verts: CSGVertex[] = [];

    for (let vi = 0; vi < vc; vi++) {
      const i = offset + vi;
      verts.push(new CSGVertex(
        new Vec3(data.positions[i * 3], data.positions[i * 3 + 1], data.positions[i * 3 + 2]),
        new Vec3(data.normals[i * 3]  ?? 0, data.normals[i * 3 + 1]   ?? 1, data.normals[i * 3 + 2]   ?? 0),
        new Vec2(data.uvs[i * 2]      ?? 0, data.uvs[i * 2 + 1]       ?? 0),
      ));
    }

    if (verts.length >= 3) polys.push(new CSGPolygon(verts, sh));
    offset += vc;
  }

  const csg = new CSG();
  csg.polygons = polys;
  return csg;
}

/** Convert flat-array mesh data directly to THREE.BufferGeometry (fan triangulation). */
export function meshDataToGeometry(data: CsgMeshData): THREE.BufferGeometry {
  const positions: number[] = [];
  const normals:   number[] = [];
  const uvs:       number[] = [];
  const indices:   number[] = [];

  let idx = 0;
  let offset = 0;

  for (const vc of data.vertexCounts) {
    const base = idx;
    for (let vi = 0; vi < vc; vi++) {
      const i = offset + vi;
      positions.push(data.positions[i * 3], data.positions[i * 3 + 1], data.positions[i * 3 + 2]);
      normals.push(data.normals[i * 3], data.normals[i * 3 + 1], data.normals[i * 3 + 2]);
      uvs.push(data.uvs[i * 2], data.uvs[i * 2 + 1]);
      idx++;
    }
    for (let i = 2; i < vc; i++) {
      indices.push(base, base + i - 1, base + i);
    }
    offset += vc;
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
  geo.setAttribute('normal',   new THREE.Float32BufferAttribute(normals,   3));
  geo.setAttribute('uv',       new THREE.Float32BufferAttribute(uvs,       2));
  geo.setIndex(indices);
  return geo;
}

// ── Async CSG operations ──────────────────────────────────────────────────────

/**
 * Run a CSG boolean operation.
 * Uses Rust/Wasm (Tauri desktop or browser Wasm) when available;
 * falls back to the pure-JS BSP implementation transparently.
 */
export async function csgOpAsync(
  a:  CsgMeshData,
  b:  CsgMeshData,
  op: 'union' | 'subtract' | 'intersect',
): Promise<CsgMeshData> {
  if (typeof (window as any).__TAURI__ !== 'undefined') {
    return (window as any).__TAURI__.core.invoke('csg_op', { a, b, op });
  }
  if (_wasmCsg) {
    const resultJson = _wasmCsg.csg_op(JSON.stringify(a), JSON.stringify(b), op);
    return JSON.parse(resultJson) as CsgMeshData;
  }
  throw new Error('[CSGBridge] No CSG backend available — run `npm run build:wasm` or use Tauri.');
}

/**
 * Batch CSG: apply an ordered list of operations against a base mesh.
 * Single round-trip on Tauri; JS fallback loops locally.
 */
export async function csgOpBatchAsync(
  base: CsgMeshData,
  ops:  { op: 'union' | 'subtract' | 'intersect'; mesh: CsgMeshData }[],
): Promise<CsgMeshData> {
  if (typeof (window as any).__TAURI__ !== 'undefined') {
    return (window as any).__TAURI__.core.invoke('csg_op_batch', { base, ops });
  }
  if (_wasmCsg) {
    const resultJson = _wasmCsg.csg_op_batch(JSON.stringify(base), JSON.stringify(ops));
    return JSON.parse(resultJson) as CsgMeshData;
  }
  throw new Error('[CSGBridge] No CSG backend available — run `npm run build:wasm` or use Tauri.');
}

/**
 * Convert CSG solid to a THREE.BufferGeometry.
 * Triangulates convex n-gon faces via fan triangulation.
 */
export function csgToGeometry(csg: CSG): THREE.BufferGeometry {
  const positions: number[] = [];
  const normals: number[] = [];
  const uvs: number[] = [];
  const indices: number[] = [];

  let idx = 0;
  for (const poly of csg.polygons) {
    const verts = poly.vertices;
    const base = idx;

    for (const v of verts) {
      positions.push(v.pos.x, v.pos.y, v.pos.z);
      normals.push(v.normal.x, v.normal.y, v.normal.z);
      uvs.push(v.uv.x, v.uv.y);
      idx++;
    }

    // Fan triangulation (polygon is convex)
    for (let i = 2; i < verts.length; i++) {
      indices.push(base, base + i - 1, base + i);
    }
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
  geo.setAttribute('normal', new THREE.Float32BufferAttribute(normals, 3));
  geo.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2));
  geo.setIndex(indices);
  return geo;
}

/**
 * Convert a THREE.BufferGeometry to a CSG solid.
 * Useful for importing external meshes into the CSG pipeline.
 */
export function geometryToCSG(geometry: THREE.BufferGeometry): CSG {
  const pos = geometry.getAttribute('position');
  const norm = geometry.getAttribute('normal');
  const uv = geometry.getAttribute('uv');
  const index = geometry.getIndex();

  const polys: CSGPolygon[] = [];
  const triCount = index ? index.count / 3 : pos.count / 3;

  for (let i = 0; i < triCount; i++) {
    const verts: CSGVertex[] = [];
    for (let j = 0; j < 3; j++) {
      const k = index ? index.getX(i * 3 + j) : i * 3 + j;
      verts.push(new CSGVertex(
        new Vec3(pos.getX(k), pos.getY(k), pos.getZ(k)),
        norm ? new Vec3(norm.getX(k), norm.getY(k), norm.getZ(k)) : new Vec3(0, 1, 0),
        uv ? new Vec2(uv.getX(k), uv.getY(k)) : new Vec2(),
      ));
    }
    polys.push(new CSGPolygon(verts));
  }

  const csg = new CSG();
  csg.polygons = polys;
  return csg;
}
