// ============================================================
// FluxionJS V3 — CSG Bridge
// Rust/Wasm-native CSG: flat-array protocol, no TS BSP fallback.
// ============================================================

import * as THREE from 'three';

// ── Types (mirror fluxion_core::csg::bridge) ──────────────────────────────────

/** Flat polygon-soup mesh — the transport format between TS and Rust CSG. */
export interface CsgMeshData {
  positions:    number[];
  normals:      number[];
  uvs:          number[];
  vertexCounts: number[];
  shared:       number[];
}

/** Parameters for building a CSG primitive in Rust. */
export interface PrimitiveRequest {
  shape:       'box' | 'cylinder' | 'cone' | 'sphere' | 'wedge' | 'stairs' | 'arch';
  cx?: number; cy?: number; cz?: number;
  sx?: number; sy?: number; sz?: number;
  radius?: number;
  height?: number;
  slices?: number;
  stacks?: number;
  radiusTop?: number;
  archRadius?: number;
  segments?: number;
  steps?: number;
  /** Column-major 4×4 matrix (16 floats). When present, applied to all verts + normals. */
  mat4?: number[];
  /** UV scale [scaleX, scaleY]. When present, multiplies all UV coordinates. */
  uvScale?: number[];
  /** UV offset [offsetX, offsetY]. When present, added to all UV coordinates after scale. */
  uvOffset?: number[];
}

// ── Wasm module slot ──────────────────────────────────────────────────────────

interface WasmCsgModule {
  csg_op(a: string, b: string, op: string): string;
  csg_op_batch(base: string, ops: string): string;
  build_csg_primitive(req: string): string;
}

let _wasmCsg: WasmCsgModule | null = null;
let _wasmLoading: Promise<void> | null = null;

/** Load the fluxion-core Wasm module for browser use. Safe to call multiple times. */
export async function initCsgCore(): Promise<void> {
  if (_wasmCsg) return;
  if (_wasmLoading) return _wasmLoading;

  _wasmLoading = (async () => {
    try {
      // @ts-ignore — generated by wasm-pack
      const mod = await import(/* webpackChunkName: "fluxion-core-csg" */ '../../fluxion-core/pkg/fluxion_core.js') as any;
      if (mod.default) await mod.default();
      _wasmCsg = mod as WasmCsgModule;
      console.info('[CSGBridge] fluxion-core Wasm loaded — using native CSG.');
    } catch {
      console.info('[CSGBridge] fluxion-core Wasm unavailable.');
    }
    _wasmLoading = null;
  })();

  return _wasmLoading;
}

/** True when the Rust/Wasm CSG path is available. */
export function isCsgNativeAvailable(): boolean {
  return _wasmCsg !== null || typeof (window as any).__TAURI__ !== 'undefined';
}

// ── Geometry converters (no CSGCore dependency) ───────────────────────────────

/** Convert CsgMeshData to a THREE.BufferGeometry via fan triangulation. */
export function meshDataToGeometry(data: CsgMeshData): THREE.BufferGeometry {
  const positions: number[] = [];
  const normals:   number[] = [];
  const uvs:       number[] = [];
  const indices:   number[] = [];

  let idx = 0;
  let offset = 0;

  for (const vc of data.vertexCounts) {
    const base = idx;
    for (let vi = 0; vi < vc; vi++) {
      const i = offset + vi;
      positions.push(data.positions[i * 3], data.positions[i * 3 + 1], data.positions[i * 3 + 2]);
      normals.push(data.normals[i * 3], data.normals[i * 3 + 1], data.normals[i * 3 + 2]);
      uvs.push(data.uvs[i * 2], data.uvs[i * 2 + 1]);
      idx++;
    }
    for (let i = 2; i < vc; i++) {
      indices.push(base, base + i - 1, base + i);
    }
    offset += vc;
  }

  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
  geo.setAttribute('normal',   new THREE.Float32BufferAttribute(normals,   3));
  geo.setAttribute('uv',       new THREE.Float32BufferAttribute(uvs,       2));
  geo.setIndex(indices);
  return geo;
}

/** Convert a THREE.BufferGeometry directly to flat CsgMeshData (triangles → shared = 0). */
export function geometryToMeshData(geometry: THREE.BufferGeometry): CsgMeshData {
  const pos   = geometry.getAttribute('position');
  const norm  = geometry.getAttribute('normal');
  const uv    = geometry.getAttribute('uv');
  const index = geometry.getIndex();

  const positions:    number[] = [];
  const normals:      number[] = [];
  const uvs:          number[] = [];
  const vertexCounts: number[] = [];
  const shared:       number[] = [];

  const triCount = index ? index.count / 3 : pos.count / 3;

  for (let i = 0; i < triCount; i++) {
    for (let j = 0; j < 3; j++) {
      const k = index ? index.getX(i * 3 + j) : i * 3 + j;
      positions.push(pos.getX(k),  pos.getY(k),  pos.getZ(k));
      normals.push(
        norm ? norm.getX(k) : 0,
        norm ? norm.getY(k) : 1,
        norm ? norm.getZ(k) : 0,
      );
      uvs.push(uv ? uv.getX(k) : 0, uv ? uv.getY(k) : 0);
    }
    vertexCounts.push(3);
    shared.push(0);
  }

  return { positions, normals, uvs, vertexCounts, shared };
}

// ── Async CSG operations ──────────────────────────────────────────────────────

/** Run a single CSG boolean operation in Rust. */
export async function csgOpAsync(
  a:  CsgMeshData,
  b:  CsgMeshData,
  op: 'union' | 'subtract' | 'intersect',
): Promise<CsgMeshData> {
  if (typeof (window as any).__TAURI__ !== 'undefined') {
    return (window as any).__TAURI__.core.invoke('csg_op', { a, b, op });
  }
  if (_wasmCsg) {
    return JSON.parse(_wasmCsg.csg_op(JSON.stringify(a), JSON.stringify(b), op)) as CsgMeshData;
  }
  throw new Error('[CSGBridge] No CSG backend — run `npm run build:wasm` or use Tauri.');
}

/** Batch CSG: apply an ordered list of boolean ops against a base mesh in one round-trip. */
export async function csgOpBatchAsync(
  base: CsgMeshData,
  ops:  { op: 'union' | 'subtract' | 'intersect'; mesh: CsgMeshData }[],
): Promise<CsgMeshData> {
  if (typeof (window as any).__TAURI__ !== 'undefined') {
    return (window as any).__TAURI__.core.invoke('csg_op_batch', { base, ops });
  }
  if (_wasmCsg) {
    return JSON.parse(_wasmCsg.csg_op_batch(JSON.stringify(base), JSON.stringify(ops))) as CsgMeshData;
  }
  throw new Error('[CSGBridge] No CSG backend — run `npm run build:wasm` or use Tauri.');
}

/** Build a CSG primitive in Rust and optionally apply a 4×4 transform. */
export async function buildPrimitiveAsync(req: PrimitiveRequest): Promise<CsgMeshData> {
  if (typeof (window as any).__TAURI__ !== 'undefined') {
    return (window as any).__TAURI__.core.invoke('build_csg_primitive', { req });
  }
  if (_wasmCsg) {
    return JSON.parse(_wasmCsg.build_csg_primitive(JSON.stringify(req))) as CsgMeshData;
  }
  throw new Error('[CSGBridge] No CSG backend — run `npm run build:wasm` or use Tauri.');
}
