// ============================================================
// FluxionJS V3 — Transform Bridge
// Thin FFI layer between TransformSystem.ts and the
// fluxion-core Wasm module's propagate_transforms export.
//
// Design goals:
//   • Synchronous — same call-site as the JS BFS (no await)
//   • Allocation-minimal — reuse typed arrays across frames
//   • Zero-config fallback — silently uses JS if Wasm absent
// ============================================================

import type { ECSManager, EntityId } from './ECS';
import type { TransformComponent } from './Components';

// ── Wasm module slot ──────────────────────────────────────────────────────────

interface WasmTransformModule {
  propagate_transforms(
    parentSlots: Int32Array,
    localData:   Float32Array,
    localDirty:  Uint8Array,
  ): Float32Array;
}

let _wasm: WasmTransformModule | null = null;
let _wasmLoading: Promise<void> | null = null;

/** Load the fluxion-core Wasm module for transform use. Safe to call multiple times. */
export async function initTransformCore(): Promise<void> {
  if (_wasm) return;
  if (_wasmLoading) return _wasmLoading;

  _wasmLoading = (async () => {
    try {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore — generated by wasm-pack, does not exist until `npm run build:wasm-csg` runs
      const mod = await import(/* webpackChunkName: "fluxion-core" */ '../../fluxion-core/pkg/fluxion_core.js') as any;
      if (mod.default) await mod.default();
      _wasm = mod as WasmTransformModule;
      console.info('[TransformBridge] fluxion-core Wasm loaded — using native transform propagation.');
    } catch {
      console.info('[TransformBridge] fluxion-core Wasm unavailable — using JS transform propagation.');
    }
    _wasmLoading = null;
  })();

  return _wasmLoading;
}

export function isTransformNativeAvailable(): boolean {
  return _wasm !== null;
}

// ── Output layout constants (must match fluxion-core/src/transform/mod.rs) ───

const OUT_STRIDE    = 27;
const OUT_FLAG_OFF  = 0;
const OUT_MAT_OFF   = 1;   // 16 floats — column-major Mat4
const OUT_POS_OFF   = 17;  // 3 floats
const OUT_ROT_OFF   = 20;  // 4 floats (x,y,z,w)
const OUT_SCL_OFF   = 24;  // 3 floats

const LOCAL_STRIDE  = 10;  // floats per entity in localData

// ── Reusable typed-array buffers (grown as needed, never shrunk) ─────────────

let _parentSlots:  Int32Array   = new Int32Array(64);
let _localData:    Float32Array = new Float32Array(64 * LOCAL_STRIDE);
let _localDirty:   Uint8Array   = new Uint8Array(64);

function _ensureCapacity(n: number): void {
  if (_parentSlots.length < n) {
    const next = Math.max(n, _parentSlots.length * 2);
    _parentSlots  = new Int32Array(next);
    _localData    = new Float32Array(next * LOCAL_STRIDE);
    _localDirty   = new Uint8Array(next);
  }
}

// ── Slot map ─────────────────────────────────────────────────────────────────

/** entityId → slot index for the current frame */
const _slotOf  = new Map<EntityId, number>();
/** slot index → entityId for the current frame */
let   _slotIds: EntityId[] = [];

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Run native-Wasm transform propagation for all entities with a TransformComponent.
 * Returns `true` if the Wasm path ran, `false` if Wasm is unavailable (caller should fallback).
 */
export function transformPropagateNative(
  entities: Set<EntityId>,
  ecs:       ECSManager,
): boolean {
  if (!_wasm) return false;

  const n = entities.size;
  if (n === 0) return true;

  _ensureCapacity(n);
  _slotOf.clear();
  if (_slotIds.length < n) _slotIds = new Array(n);

  // ── Pass 1: assign slots + pack local TRS data ────────────────────────────
  let slot = 0;
  for (const eid of entities) {
    _slotOf.set(eid, slot);
    _slotIds[slot] = eid;
    slot++;
  }

  for (let i = 0; i < n; i++) {
    const eid = _slotIds[i];
    const t   = ecs.getComponent<TransformComponent>(eid, 'Transform');

    if (t) {
      const base = i * LOCAL_STRIDE;
      _localData[base    ] = t.position.x;
      _localData[base + 1] = t.position.y;
      _localData[base + 2] = t.position.z;
      _localData[base + 3] = t.quaternion.x;
      _localData[base + 4] = t.quaternion.y;
      _localData[base + 5] = t.quaternion.z;
      _localData[base + 6] = t.quaternion.w;
      _localData[base + 7] = t.scale.x;
      _localData[base + 8] = t.scale.y;
      _localData[base + 9] = t.scale.z;

      _localDirty[i] = (t.dirty || t.worldDirty) ? 1 : 0;
    } else {
      // No transform — identity, never dirty
      const base = i * LOCAL_STRIDE;
      _localData[base    ] = 0; _localData[base + 1] = 0; _localData[base + 2] = 0;
      _localData[base + 3] = 0; _localData[base + 4] = 0; _localData[base + 5] = 0; _localData[base + 6] = 1;
      _localData[base + 7] = 1; _localData[base + 8] = 1; _localData[base + 9] = 1;
      _localDirty[i] = 0;
    }

    // Parent slot
    const parentId = ecs.getParent(eid);
    _parentSlots[i] = parentId !== undefined ? (_slotOf.get(parentId) ?? -1) : -1;
  }

  // ── Note: parent slots are filled in a second pass because some parent IDs
  //    may not have been assigned a slot yet in pass 1.
  // Re-fill parent slots now that all IDs are in the map:
  for (let i = 0; i < n; i++) {
    const eid      = _slotIds[i];
    const parentId = ecs.getParent(eid);
    _parentSlots[i] = parentId !== undefined ? (_slotOf.get(parentId) ?? -1) : -1;
  }

  // ── Call Wasm (synchronous) ───────────────────────────────────────────────
  const parentView = _parentSlots.subarray(0, n);
  const localView  = _localData.subarray(0, n * LOCAL_STRIDE);
  const dirtyView  = _localDirty.subarray(0, n);

  const output = _wasm.propagate_transforms(parentView, localView, dirtyView);

  // ── Pass 2: write results back to TransformComponents ────────────────────
  for (let i = 0; i < n; i++) {
    const base = i * OUT_STRIDE;
    if (output[base + OUT_FLAG_OFF] === 0) continue; // not updated — skip

    const eid = _slotIds[i];
    const t   = ecs.getComponent<TransformComponent>(eid, 'Transform');
    if (!t) continue;

    // World matrix (column-major)
    t._worldMatrix.fromArray(output as unknown as number[], base + OUT_MAT_OFF);

    // World decomposed
    t.worldPosition.set(
      output[base + OUT_POS_OFF],
      output[base + OUT_POS_OFF + 1],
      output[base + OUT_POS_OFF + 2],
    );
    t.worldRotation.set(
      output[base + OUT_ROT_OFF],
      output[base + OUT_ROT_OFF + 1],
      output[base + OUT_ROT_OFF + 2],
      output[base + OUT_ROT_OFF + 3],
    );
    t.worldScale.set(
      output[base + OUT_SCL_OFF],
      output[base + OUT_SCL_OFF + 1],
      output[base + OUT_SCL_OFF + 2],
    );

    t.dirty      = false;
    t.worldDirty = false;
  }

  return true;
}
