// ============================================================
// FluxionJS V3 — JavaScript API Generator
// Generates fluxion.js: a runtime module with JSDoc annotations
// so VS Code's JavaScript language server provides intellisense.
// User scripts can: const { FluxionBehaviour } = require('./fluxion');
// ============================================================

import type { EngineDef, ComponentDef, FieldDef } from '../MetaTypes';

// ── Shared math-type @typedef block ──────────────────────────────────────────
// Emitted once at the top of the generated file so all component @property
// annotations can reference Vector2, Vector3, Color, etc. by name.

const JS_SHARED_TYPES = `\
// ── Shared math types ────────────────────────────────────────────────────────

/** @typedef {{ x: number, y: number }} Vector2 */
/** @typedef {{ x: number, y: number, z: number }} Vector3 */
/** @typedef {{ x: number, y: number, z: number, order: string }} Euler */
/** @typedef {{ x: number, y: number, z: number, w: number }} Quaternion */
/** @typedef {{ r: number, g: number, b: number }} Color */
`;

function _primitiveJsType(t: string): string {
  switch (t) {
    case 'number': case 'slider': return 'number';
    case 'boolean': return 'boolean';
    case 'string': return 'string';
    case 'vector3': return 'Vector3';
    case 'euler':   return 'Euler';
    case 'vector2': return 'Vector2';
    case 'color':   return 'Color';
    case 'asset': return 'string|null';
    default: return '*';
  }
}

function fieldToJsDocType(f: FieldDef): string {
  switch (f.type) {
    case 'number':
    case 'slider':   return 'number';
    case 'boolean':  return 'boolean';
    case 'string':   return 'string';
    case 'vector3':  return 'Vector3';
    case 'euler':    return 'Euler';
    case 'vector2':  return 'Vector2';
    case 'color':    return 'Color';
    case 'select':
      if (f.options?.length) {
        return f.options.map(o => `'${o.value}'`).join('|');
      }
      return 'string';
    case 'asset':    return 'string|null';
    case 'array':
      if (f.tupleTypes?.length) return `[${f.tupleTypes.map(_primitiveJsType).join(', ')}]`;
      return f.itemType ? `${_primitiveJsType(f.itemType)}[]` : 'Array';
    case 'union':
      return f.unionTypes?.length
        ? f.unionTypes.map(_primitiveJsType).join('|')
        : '*';
    default:         return '*';
  }
}

function emitTypedef(c: ComponentDef): string {
  const isScript = c.category === 'Scripts';
  const className = isScript ? c.typeId.replace(/^Script:/, '') : c.typeId;

  const fieldProps = c.fields.map(f => {
    const jsType = fieldToJsDocType(f);
    return `${f.key}: ${jsType}`;
  });

  const compDesc = c.description ? ` — ${c.description}` : '';

  if (isScript) {
    // Script classes: @typedef {FluxionBehaviour & { speed: number }} PlayerController
    const intersection = fieldProps.length
      ? `FluxionBehaviour & { ${fieldProps.join(', ')} }`
      : 'FluxionBehaviour';
    const lines: string[] = [`/**`];
    if (c.deprecated) lines.push(` * @deprecated`);
    lines.push(
      ` * @typedef {${intersection}} ${className}`,
      ` * @description Script: ${c.displayName}${compDesc}`,
      ` */`,
    );
    return lines.join('\n');
  }

  // Normal component
  const lines: string[] = [
    `/**`,
  ];
  if (c.deprecated) lines.push(` * @deprecated`);
  lines.push(
    ` * @typedef {Object} ${className}`,
    ` * @description [${c.category}] ${c.displayName} component${compDesc}`,
    ` * @property {boolean} enabled Whether this component is active`,
  );
  for (const f of c.fields) {
    const jsType = fieldToJsDocType(f);
    const label  = f.label !== f.key ? f.label : f.key;
    const fieldDesc = f.description ? ` — ${f.description}` : '';
    if (f.readOnly) lines.push(` * @readonly`);
    lines.push(` * @property {${jsType}} ${f.optional ? `[${f.key}]` : f.key} ${label}${fieldDesc}`);
  }
  lines.push(` */`);
  return lines.join('\n');
}

const JS_RUNTIME = `\
// ============================================================
// FluxionJS V3 — Auto-generated JavaScript API
// Generated by MetaSystem — do not edit manually.
// JSDoc annotations provide VS Code intellisense for .js scripts.
// ============================================================

'use strict';

/**
 * Base class for all FluxionJS user scripts (JavaScript version).
 *
 * Usage:
 *   const { FluxionBehaviour } = require('./fluxion');
 *   module.exports = class MyScript extends FluxionBehaviour {
 *     start() { this.log('Hello from', this.constructor.name); }
 *     update(dt) { }
 *   };
 */
class FluxionBehaviour {
  constructor() {
    /** @type {number} The entity ID this script is attached to. */
    this.entity = 0;
    /** @internal */ this._ecs = null;
    /** @internal */ this._engine = null;
    /** @internal */ this._input = null;
    /** @internal */ this._renderer = null;
    /** @internal */ this._audio = null;
    /** @internal */ this._cleanupFns = [];
    /** @internal */ this._coroutines = new Map();
    /** @internal */ this._started = false;
  }

  // Lifecycle stubs — override in subclass
  start() {}
  update(_dt) {}
  fixedUpdate(_dt) {}
  lateUpdate(_dt) {}
  onDestroy() {}
  onEnable() {}
  onDisable() {}
}

module.exports = { FluxionBehaviour };
`;

export class JavaScriptGenerator {
  static generate(def: EngineDef): string {
    const typedefs = def.components.map(emitTypedef).join('\n\n');
    return `${JS_SHARED_TYPES}\n${typedefs}\n\n${JS_RUNTIME}`;
  }
}
