// ============================================================
// FluxionJS V3 — Lua API Generator
// Generates fluxion.lua with EmmyLua (--- @) annotations for
// Lua Language Server (sumneko/lua-language-server).
// Provides class definitions, field types, and method stubs
// so Lua scripts get intellisense in VS Code / ZeroBrane.
// ============================================================

import type { EngineDef, ComponentDef, FieldDef } from '../MetaTypes';

function _primitiveLuaType(t: string): string {
  switch (t) {
    case 'number': case 'slider': return 'number';
    case 'boolean': return 'boolean';
    case 'string': return 'string';
    case 'vector3': case 'euler': return 'Vector3';
    case 'vector2': return 'Vector2';
    case 'color': return 'Color';
    case 'asset': return 'string|nil';
    default: return 'any';
  }
}

function fieldToLuaType(f: FieldDef): string {
  switch (f.type) {
    case 'number':
    case 'slider':   return 'number';
    case 'boolean':  return 'boolean';
    case 'string':   return 'string';
    case 'vector3':
    case 'euler':    return 'Vector3';
    case 'vector2':  return 'Vector2';
    case 'color':    return 'Color';
    case 'select':
      if (f.options?.length) {
        return f.options.map(o => `"${o.value}"`).join('|');
      }
      return 'string';
    case 'asset':    return 'string|nil';
    case 'array':
      if (f.tupleTypes?.length) return 'table';
      return f.itemType ? `${_primitiveLuaType(f.itemType)}[]` : 'table';
    case 'union':
      return f.unionTypes?.length
        ? f.unionTypes.map(_primitiveLuaType).join('|')
        : 'any';
    default:         return 'any';
  }
}

function emitComponentLua(c: ComponentDef): string {
  const isScript = c.category === 'Scripts';
  const className = isScript ? c.typeId.replace(/^Script:/, '') : c.typeId;
  const baseClass = isScript ? 'FluxionBehaviour' : 'Component';
  const descSuffix = c.description ? ` ── ${c.description}` : '';

  const lines: string[] = [
    `-- ── ${c.displayName} [${c.category}]${descSuffix} ${'─'.repeat(Math.max(0, 42 - c.displayName.length - descSuffix.length))}`,
  ];
  if (c.deprecated) lines.push(`--- @deprecated`);
  lines.push(`--- @class ${className} : ${baseClass}`);
  if (!isScript) {
    lines.push(`--- @field enabled boolean Whether this component is active`);
  }
  for (const f of c.fields) {
    const luaType = fieldToLuaType(f);
    const opt     = f.optional ? '?' : '';
    const label   = f.label !== f.key ? f.label : f.key;
    const fieldDesc = f.description ? ` — ${f.description}` : '';
    const rdOnly  = f.readOnly ? ' (readonly)' : '';
    lines.push(`--- @field ${f.key}${opt} ${luaType} ${label}${rdOnly}${fieldDesc}`);
  }
  lines.push(`${className} = {}`);
  lines.push('');
  return lines.join('\n');
}

const LUA_STATIC_HEADER = `\
--[[
  FluxionJS V3 — Auto-generated Lua Script API
  Generated by MetaSystem — do not edit manually.

  For EmmyLua / Lua Language Server intellisense:
  Add this file to your Lua workspace via:
    settings > Lua > workspace.library = [".fluxion/api"]

  Usage:
    --- @type FluxionBehaviour
    local self = FluxionBehaviour:new()
--]]

-- @meta

-- ── Primitive types ─────────────────────────────────────────

--- @class Vector3
--- @field x number
--- @field y number
--- @field z number
Vector3 = {}
--- @param x number
--- @param y number
--- @param z number
--- @return Vector3
function Vector3:new(x, y, z) return {} end
--- @return Vector3
function Vector3:clone() return {} end
--- @param v Vector3
--- @return Vector3
function Vector3:add(v) return self end
--- @param s number
--- @return Vector3
function Vector3:multiplyScalar(s) return self end
--- @return number
function Vector3:length() return 0 end
--- @return Vector3
function Vector3:normalize() return self end

--- @class Vector2
--- @field x number
--- @field y number
Vector2 = {}

--- @class Quaternion
--- @field x number
--- @field y number
--- @field z number
--- @field w number
Quaternion = {}

--- @class Color
--- @field r number
--- @field g number
--- @field b number
Color = {}

--- @class Euler
--- @field x number
--- @field y number
--- @field z number
--- @field order string
Euler = {}

-- ── Engine APIs ──────────────────────────────────────────────

--- @class Transform
--- @field position Vector3 Local position
--- @field rotation Euler Local Euler rotation
--- @field scale Vector3 Local scale
--- @field quaternion Quaternion Local quaternion
--- @field worldPosition Vector3 World-space position (read-only)
--- @field worldRotation Quaternion World-space rotation (read-only)
--- @field localPosition Vector3 Local-space position
--- @field localRotation Euler Local-space rotation
--- @field localScale Vector3 Local-space scale
--- @field parent number|nil Parent entity ID
--- @field children number[] Child entity IDs
Transform = {}

--- @class TimeAPI
--- @field deltaTime number Seconds since last frame
--- @field fixedDeltaTime number Fixed timestep in seconds
--- @field elapsed number Total elapsed time
--- @field frameCount number Total frame count
--- @field fps number Current frames per second
--- @field timeScale number Simulation speed multiplier
TimeAPI = {}

--- @class InputAPI
--- @field mousePosition Vector2
--- @field mouseDelta Vector2
--- @field mouseWheel number
--- @field horizontal number
--- @field vertical number
InputAPI = {}
--- @param code string Key code e.g. "KeyW", "Space"
--- @return boolean
function InputAPI:isKeyDown(code) return false end
--- @param code string
--- @return boolean
function InputAPI:isKeyPressed(code) return false end
--- @param code string
--- @return boolean
function InputAPI:isKeyReleased(code) return false end
--- @param button? number Mouse button index (0=left, 1=right, 2=middle)
--- @return boolean
function InputAPI:isMouseDown(button) return false end

--- @class RaycastHit
--- @field entityId number
--- @field point Vector3
--- @field normal Vector3
--- @field distance number
RaycastHit = {}

--- @class PhysicsAPI
PhysicsAPI = {}
--- @param origin Vector3
--- @param direction Vector3
--- @param maxDistance? number
--- @return RaycastHit|nil
function PhysicsAPI:raycast(origin, direction, maxDistance) return nil end

--- @class DebugAPI
DebugAPI = {}
--- @param ... any
function DebugAPI:log(...) end
--- @param ... any
function DebugAPI:warn(...) end
--- @param ... any
function DebugAPI:error(...) end
--- @param start Vector3
--- @param stop Vector3
--- @param color? Color
function DebugAPI:drawLine(start, stop, color) end

--- @class SceneAPI
--- @field name string Current scene name
SceneAPI = {}
--- @param path string
function SceneAPI:load(path) end

--- @class Component
--- @field enabled boolean
Component = {}

`;

const LUA_BEHAVIOUR = `\
-- ── FluxionBehaviour base class ─────────────────────────────

--- @class FluxionBehaviour
--- @field entity number The entity ID this script is attached to
--- @field transform Transform Shortcut to this entity's Transform
--- @field Time TimeAPI
--- @field Input InputAPI
--- @field Physics PhysicsAPI
--- @field Debug DebugAPI
--- @field Scene SceneAPI
FluxionBehaviour = {}

--- @param typeId string
--- @return any|nil
function FluxionBehaviour:getComponent(typeId) return nil end

--- @param entityId number
--- @param typeId string
--- @return any|nil
function FluxionBehaviour:getComponentOf(entityId, typeId) return nil end

--- @param typeId string
--- @return boolean
function FluxionBehaviour:hasComponent(typeId) return false end

--- @param name string
--- @return number|nil Entity ID
function FluxionBehaviour:find(name) return nil end

--- @param tag string
--- @return number|nil Entity ID
function FluxionBehaviour:findWithTag(tag) return nil end

--- @param tag string
--- @return number[] Entity IDs
function FluxionBehaviour:findAll(tag) return {} end

--- @param name? string
--- @return number Entity ID
function FluxionBehaviour:createEntity(name) return 0 end

--- @param entityId? number Defaults to this entity
function FluxionBehaviour:destroy(entityId) end

--- @param event string
--- @param callback function
--- @param priority? number
function FluxionBehaviour:on(event, callback, priority) end

--- @param event string
--- @param data? any
function FluxionBehaviour:emit(event, data) end

--- @param gen any Generator function
--- @return any Coroutine handle
function FluxionBehaviour:startCoroutine(gen) return nil end

--- @param handle any
function FluxionBehaviour:stopCoroutine(handle) end

--- @param tag string
--- @param entityId? number
function FluxionBehaviour:addTag(tag, entityId) end

--- @param tag string
--- @param entityId? number
--- @return boolean
function FluxionBehaviour:hasTag(tag, entityId) return false end

--- @param ... any
function FluxionBehaviour:log(...) end
--- @param ... any
function FluxionBehaviour:warn(...) end
--- @param ... any
function FluxionBehaviour:error(...) end

-- Lifecycle hooks — override in subclass
--- Called once when the script first activates
function FluxionBehaviour:start() end
--- Called every frame
--- @param deltaTime number
function FluxionBehaviour:update(deltaTime) end
--- Called at fixed physics timestep
--- @param deltaTime number
function FluxionBehaviour:fixedUpdate(deltaTime) end
--- Called after all update() calls this frame
--- @param deltaTime number
function FluxionBehaviour:lateUpdate(deltaTime) end
--- Called when entity is destroyed or scene is cleared
function FluxionBehaviour:onDestroy() end
--- Called when script becomes enabled
function FluxionBehaviour:onEnable() end
--- Called when script becomes disabled
function FluxionBehaviour:onDisable() end
`;

export class LuaGenerator {
  static generate(def: EngineDef): string {
    const parts: string[] = [LUA_STATIC_HEADER];

    // Group by category
    const byCategory = new Map<string, ComponentDef[]>();
    for (const c of def.components) {
      const cat = c.category;
      const arr = byCategory.get(cat) ?? [];
      arr.push(c);
      byCategory.set(cat, arr);
    }

    for (const [cat, comps] of byCategory) {
      parts.push(`-- ╔══ ${cat} ${'═'.repeat(Math.max(2, 44 - cat.length))}╗`);
      for (const c of comps) {
        parts.push(emitComponentLua(c));
      }
    }

    parts.push(LUA_BEHAVIOUR);
    return parts.join('\n');
  }
}
