// ============================================================
// FluxionJS V3 — Lua API Generator
// Generates fluxion.lua with EmmyLua (--- @) annotations for
// Lua Language Server (sumneko/lua-language-server).
// Provides class definitions, field types, and method stubs
// so Lua scripts get intellisense in VS Code / ZeroBrane.
// ============================================================

import type { EngineDef, ComponentDef, FieldDef } from '../MetaTypes';

function _primitiveLuaType(t: string): string {
  switch (t) {
    case 'number': case 'slider': return 'number';
    case 'boolean': return 'boolean';
    case 'string': return 'string';
    case 'vector3': case 'euler': return 'Vector3';
    case 'vector2': return 'Vector2';
    case 'color': return 'Color';
    case 'asset': return 'string|nil';
    default: return 'any';
  }
}

function fieldToLuaType(f: FieldDef): string {
  switch (f.type) {
    case 'number':
    case 'slider':   return 'number';
    case 'boolean':  return 'boolean';
    case 'string':   return 'string';
    case 'vector3':
    case 'euler':    return 'Vector3';
    case 'vector2':  return 'Vector2';
    case 'color':    return 'Color';
    case 'select':
      if (f.options?.length) {
        return f.options.map(o => `"${o.value}"`).join('|');
      }
      return 'string';
    case 'asset':    return 'string|nil';
    case 'array':
      if (f.tupleTypes?.length) return 'table';
      return f.itemType ? `${_primitiveLuaType(f.itemType)}[]` : 'table';
    case 'union':
      return f.unionTypes?.length
        ? f.unionTypes.map(_primitiveLuaType).join('|')
        : 'any';
    default:         return 'any';
  }
}

function emitComponentLua(c: ComponentDef): string {
  const isScript = c.category === 'Scripts';
  const className = isScript ? c.typeId.replace(/^Script:/, '') : c.typeId;
  const baseClass = isScript ? 'FluxionBehaviour' : 'Component';
  const descSuffix = c.description ? ` ── ${c.description}` : '';

  const lines: string[] = [
    `-- ── ${c.displayName} [${c.category}]${descSuffix} ${'─'.repeat(Math.max(0, 42 - c.displayName.length - descSuffix.length))}`,
  ];
  if (c.deprecated) lines.push(`--- @deprecated`);
  lines.push(`--- @class ${className} : ${baseClass}`);
  if (!isScript) {
    lines.push(`--- @field enabled boolean Whether this component is active`);
  }
  for (const f of c.fields) {
    const luaType = fieldToLuaType(f);
    const opt     = f.optional ? '?' : '';
    const label   = f.label !== f.key ? f.label : f.key;
    const fieldDesc = f.description ? ` — ${f.description}` : '';
    const rdOnly  = f.readOnly ? ' (readonly)' : '';
    lines.push(`--- @field ${f.key}${opt} ${luaType} ${label}${rdOnly}${fieldDesc}`);
  }
  lines.push(`${className} = {}`);
  lines.push('');
  return lines.join('\n');
}

const LUA_STATIC_HEADER = `\
--[[
  FluxionJS V3 — Auto-generated Lua Script API
  Generated by MetaSystem — do not edit manually.

  For EmmyLua / Lua Language Server intellisense:
  Add this file to your Lua workspace via:
    settings > Lua > workspace.library = [".fluxion/api"]

  Usage:
    --- @type FluxionBehaviour
    local self = FluxionBehaviour:new()
--]]

-- @meta

-- ── Primitive types ─────────────────────────────────────────

--- @class Vector3
--- @field x number
--- @field y number
--- @field z number
Vector3 = {}
--- @param x number
--- @param y number
--- @param z number
--- @return Vector3
function Vector3:new(x, y, z) return {} end
--- @return Vector3
function Vector3:clone() return {} end
--- @param v Vector3
--- @return Vector3
function Vector3:add(v) return self end
--- @param s number
--- @return Vector3
function Vector3:multiplyScalar(s) return self end
--- @return number
function Vector3:length() return 0 end
--- @return Vector3
function Vector3:normalize() return self end

--- @class Vector2
--- @field x number
--- @field y number
Vector2 = {}

--- @class Quaternion
--- @field x number
--- @field y number
--- @field z number
--- @field w number
Quaternion = {}

--- @class Color
--- @field r number
--- @field g number
--- @field b number
Color = {}

--- @class Euler
--- @field x number
--- @field y number
--- @field z number
--- @field order string
Euler = {}

-- ── Engine APIs ──────────────────────────────────────────────

--- @class Transform
--- @field position Vector3 Local position
--- @field rotation Euler Local Euler rotation (radians)
--- @field scale Vector3 Local scale
--- @field worldPosition Vector3 World-space position (readonly)
--- @field worldRotation Euler World-space Euler rotation (readonly)
--- @field worldScale Vector3 World-space scale (readonly)
--- @field parent number|nil Parent entity ID
--- @field children number[] Child entity IDs
Transform = {}

--- @class TimeAPI
--- @field deltaTime number Seconds since last frame
--- @field fixedDeltaTime number Fixed timestep in seconds
--- @field elapsed number Total elapsed time
--- @field frameCount number Total frame count
--- @field fps number Current frames per second
--- @field timeScale number Simulation speed multiplier
TimeAPI = {}

--- @class InputAPI
--- @field mousePosition Vector2
--- @field mouseDelta Vector2
--- @field mouseWheel number
--- @field horizontal number
--- @field vertical number
InputAPI = {}
--- @param code string Key code e.g. "KeyW", "Space"
--- @return boolean
function InputAPI:isKeyDown(code) return false end
--- @param code string
--- @return boolean
function InputAPI:isKeyPressed(code) return false end
--- @param code string
--- @return boolean
function InputAPI:isKeyReleased(code) return false end
--- @param button? number Mouse button index (0=left, 1=right, 2=middle)
--- @return boolean
function InputAPI:isMouseDown(button) return false end

--- @class RaycastHit
--- @field entityId number
--- @field point Vector3
--- @field normal Vector3
--- @field distance number
RaycastHit = {}

--- @class PhysicsAPI
PhysicsAPI = {}
--- @param origin Vector3
--- @param direction Vector3
--- @param maxDistance? number
--- @return RaycastHit|nil
function PhysicsAPI:raycast(origin, direction, maxDistance) return nil end

--- @class DebugAPI
DebugAPI = {}
--- @param ... any
function DebugAPI:log(...) end
--- @param ... any
function DebugAPI:warn(...) end
--- @param ... any
function DebugAPI:error(...) end
--- @param start Vector3
--- @param stop Vector3
--- @param color? Color
function DebugAPI:drawLine(start, stop, color) end

--- @class SceneAPI
--- @field name string Current scene name
SceneAPI = {}
--- @param path string
function SceneAPI:load(path) end

--- @class Component
--- @field enabled boolean
Component = {}

`;

const LUA_BEHAVIOUR_HEAD = `\
-- ── FluxionBehaviour base class ─────────────────────────────
--
-- Two access layers are available:
--
--   gameObject  (high-level) — preferred API for component access,
--               hierarchy traversal, and scene queries.
--               Example: local rb = self:getComponent("Rigidbody")
--
--   entity      (low-level)  — raw ECS entity ID (integer).
--               Use only when a function explicitly requires a numeric ID,
--               e.g. getComponentOf, getParent, physics force calls.
--               gameObject wraps this same ID internally.

--- @class FluxionBehaviour
--- @field entity number Low-level ECS entity ID. Prefer gameObject for most operations.
--- @field transform Transform Shortcut to this entity's Transform (high-level alias).
--- @field Time TimeAPI
--- @field Input InputAPI
--- @field Physics PhysicsAPI
--- @field Debug DebugAPI
--- @field Scene SceneAPI
FluxionBehaviour = {}
`;

const LUA_BEHAVIOUR_TAIL = `\
--- @param typeId string
--- @return boolean
function FluxionBehaviour:hasComponent(typeId) return false end

--- @param name string
--- @return number|nil Entity ID
function FluxionBehaviour:find(name) return nil end

--- @param tag string
--- @return number|nil Entity ID
function FluxionBehaviour:findWithTag(tag) return nil end

--- @param tag string
--- @return number[] Entity IDs
function FluxionBehaviour:findAll(tag) return {} end

--- @param name? string
--- @return number Entity ID
function FluxionBehaviour:createEntity(name) return 0 end

--- @param entityId? number Defaults to this entity
function FluxionBehaviour:destroy(entityId) end

--- @param event string
--- @param callback function
--- @param priority? number
function FluxionBehaviour:on(event, callback, priority) end

--- @param event string
--- @param data? any
function FluxionBehaviour:emit(event, data) end

--- @param gen any Generator function
--- @return any Coroutine handle
function FluxionBehaviour:startCoroutine(gen) return nil end

--- @param handle any
function FluxionBehaviour:stopCoroutine(handle) end

--- @param tag string
--- @param entityId? number
function FluxionBehaviour:addTag(tag, entityId) end

--- @param tag string
--- @param entityId? number
--- @return boolean
function FluxionBehaviour:hasTag(tag, entityId) return false end

--- @param ... any
function FluxionBehaviour:log(...) end
--- @param ... any
function FluxionBehaviour:warn(...) end
--- @param ... any
function FluxionBehaviour:error(...) end

-- Lifecycle hooks — override in subclass
--- Called once when the script first activates
function FluxionBehaviour:start() end
--- Called every frame
--- @param deltaTime number
function FluxionBehaviour:update(deltaTime) end
--- Called at fixed physics timestep
--- @param deltaTime number
function FluxionBehaviour:fixedUpdate(deltaTime) end
--- Called after all update() calls this frame
--- @param deltaTime number
function FluxionBehaviour:lateUpdate(deltaTime) end
--- Called when entity is destroyed or scene is cleared
function FluxionBehaviour:onDestroy() end
--- Called when script becomes enabled
function FluxionBehaviour:onEnable() end
--- Called when script becomes disabled
function FluxionBehaviour:onDisable() end
`;

// ── Component access emitter ──────────────────────────────────

function emitLuaComponentAccess(def: EngineDef): string {
  const nonScripts = def.components.filter(c => c.category !== 'Scripts');

  const aliasLines = nonScripts.map(c => `  | "${c.typeId}"`).join('\n');

  const gcOverloads = nonScripts
    .map(c => `--- @overload fun(self: FluxionBehaviour, typeId: "${c.typeId}"): ${c.typeId}|nil`)
    .join('\n');

  const gcoOverloads = nonScripts
    .map(c => `--- @overload fun(self: FluxionBehaviour, entityId: number, typeId: "${c.typeId}"): ${c.typeId}|nil`)
    .join('\n');

  return [
    `-- ── Component type alias ───────────────────────────────────`,
    ``,
    `--- @alias ComponentType`,
    aliasLines,
    ``,
    ``,
    gcOverloads,
    `--- @param typeId ComponentType`,
    `--- @return any|nil`,
    `function FluxionBehaviour:getComponent(typeId) return nil end`,
    ``,
    `-- Low-level: takes a raw entity ID. Prefer self:getComponent() on this entity.`,
    gcoOverloads,
    `--- @param entityId number Raw ECS entity ID (low-level)`,
    `--- @param typeId ComponentType`,
    `--- @return any|nil`,
    `function FluxionBehaviour:getComponentOf(entityId, typeId) return nil end`,
    ``,
  ].join('\n');
}

// ── Main export ──────────────────────────────────────────────

export class LuaGenerator {
  static generate(def: EngineDef): string {
    const parts: string[] = [LUA_STATIC_HEADER];

    // Group by category
    const byCategory = new Map<string, ComponentDef[]>();
    for (const c of def.components) {
      const cat = c.category;
      const arr = byCategory.get(cat) ?? [];
      arr.push(c);
      byCategory.set(cat, arr);
    }

    for (const [cat, comps] of byCategory) {
      parts.push(`-- ╔══ ${cat} ${'═'.repeat(Math.max(2, 44 - cat.length))}╗`);
      for (const c of comps) {
        parts.push(emitComponentLua(c));
      }
    }

    parts.push(LUA_BEHAVIOUR_HEAD);
    parts.push(emitLuaComponentAccess(def));
    parts.push(LUA_BEHAVIOUR_TAIL);
    parts.push(LUA_UTIL_FUNCTIONS);
    return parts.join('\n');
  }
}

const LUA_UTIL_FUNCTIONS = `
-- ── Pure utility functions ───────────────────────────────────
-- Stateless functional alternatives to class methods.
-- All functions return new values — inputs are never mutated.

-- ── Constructors ─────────────────────────────────────────────

--- @param x number @param y number @param z number @return Vector3
function vec3(x, y, z) return Vector3:new(x, y, z) end

--- @param x number @param y number @return Vector2
function vec2(x, y) return { x=x, y=y } end

--- Create a Color from r/g/b components in the [0, 1] range.
--- @param r number @param g number @param b number @return Color
function color(r, g, b) return { r=r, g=g, b=b } end

--- Create a Color from a CSS hex string, e.g. "#ff8800".
--- @param hex string @return Color
function color_hex(hex) return { r=0, g=0, b=0 } end

-- ── Vector3 ──────────────────────────────────────────────────

--- @param a Vector3 @param b Vector3 @return Vector3
function vec3_add(a, b) return vec3(a.x+b.x, a.y+b.y, a.z+b.z) end

--- @param a Vector3 @param b Vector3 @return Vector3
function vec3_sub(a, b) return vec3(a.x-b.x, a.y-b.y, a.z-b.z) end

--- Multiply a Vector3 by a scalar.
--- @param a Vector3 @param s number @return Vector3
function vec3_mul(a, s) return vec3(a.x*s, a.y*s, a.z*s) end

--- Divide a Vector3 by a scalar.
--- @param a Vector3 @param s number @return Vector3
function vec3_div(a, s) return vec3(a.x/s, a.y/s, a.z/s) end

--- Negate a Vector3 (all components × -1).
--- @param a Vector3 @return Vector3
function vec3_neg(a) return vec3(-a.x, -a.y, -a.z) end

--- @param a Vector3 @param b Vector3 @return number
function vec3_dot(a, b) return a.x*b.x + a.y*b.y + a.z*b.z end

--- @param a Vector3 @param b Vector3 @return Vector3
function vec3_cross(a, b)
  return vec3(a.y*b.z - a.z*b.y, a.z*b.x - a.x*b.z, a.x*b.y - a.y*b.x)
end

--- Euclidean length of a Vector3.
--- @param a Vector3 @return number
function vec3_length(a) return math.sqrt(a.x*a.x + a.y*a.y + a.z*a.z) end

--- Squared length — avoids a sqrt; useful for comparisons.
--- @param a Vector3 @return number
function vec3_length_sq(a) return a.x*a.x + a.y*a.y + a.z*a.z end

--- @param a Vector3 @return Vector3
function vec3_normalize(a)
  local l = vec3_length(a)
  return l > 0 and vec3_div(a, l) or vec3(0, 0, 0)
end

--- Linearly interpolate between a and b by t in [0, 1].
--- @param a Vector3 @param b Vector3 @param t number @return Vector3
function vec3_lerp(a, b, t)
  return vec3(a.x+(b.x-a.x)*t, a.y+(b.y-a.y)*t, a.z+(b.z-a.z)*t)
end

--- @param a Vector3 @param b Vector3 @return number
function vec3_distance(a, b) return vec3_length(vec3_sub(a, b)) end

--- Squared distance — avoids a sqrt.
--- @param a Vector3 @param b Vector3 @return number
function vec3_distance_sq(a, b) return vec3_length_sq(vec3_sub(a, b)) end

--- Reflect a direction vector off a surface with the given outward normal.
--- @param dir Vector3 @param normal Vector3 @return Vector3
function vec3_reflect(dir, normal)
  local d = 2 * vec3_dot(dir, normal)
  return vec3_sub(dir, vec3_mul(normal, d))
end

--- Project vector a onto vector b.
--- @param a Vector3 @param b Vector3 @return Vector3
function vec3_project(a, b)
  local bb = vec3_length_sq(b)
  return bb > 0 and vec3_mul(b, vec3_dot(a, b) / bb) or vec3(0, 0, 0)
end

--- Unsigned angle in radians between two direction vectors.
--- @param a Vector3 @param b Vector3 @return number
function vec3_angle(a, b)
  local d = vec3_dot(vec3_normalize(a), vec3_normalize(b))
  return math.acos(math.max(-1, math.min(1, d)))
end

-- ── Vector2 ──────────────────────────────────────────────────

--- @param a Vector2 @param b Vector2 @return Vector2
function vec2_add(a, b) return vec2(a.x+b.x, a.y+b.y) end

--- @param a Vector2 @param b Vector2 @return Vector2
function vec2_sub(a, b) return vec2(a.x-b.x, a.y-b.y) end

--- @param a Vector2 @param s number @return Vector2
function vec2_mul(a, s) return vec2(a.x*s, a.y*s) end

--- @param a Vector2 @param b Vector2 @return number
function vec2_dot(a, b) return a.x*b.x + a.y*b.y end

--- @param a Vector2 @return number
function vec2_length(a) return math.sqrt(a.x*a.x + a.y*a.y) end

--- @param a Vector2 @return Vector2
function vec2_normalize(a)
  local l = vec2_length(a)
  return l > 0 and vec2_mul(a, 1/l) or vec2(0, 0)
end

--- @param a Vector2 @param b Vector2 @param t number @return Vector2
function vec2_lerp(a, b, t) return vec2(a.x+(b.x-a.x)*t, a.y+(b.y-a.y)*t) end

--- Unsigned angle in radians between two Vector2 directions.
--- @param a Vector2 @param b Vector2 @return number
function vec2_angle(a, b)
  local d = vec2_dot(a, b) / (vec2_length(a) * vec2_length(b))
  return math.acos(math.max(-1, math.min(1, d)))
end

-- ── Color ─────────────────────────────────────────────────────

--- @param a Color @param b Color @param t number @return Color
function color_lerp(a, b, t)
  return color(a.r+(b.r-a.r)*t, a.g+(b.g-a.g)*t, a.b+(b.b-a.b)*t)
end

--- Scale all color components by a scalar.
--- @param c Color @param s number @return Color
function color_mul(c, s) return color(c.r*s, c.g*s, c.b*s) end

--- Add two colors component-wise.
--- @param a Color @param b Color @return Color
function color_add(a, b) return color(a.r+b.r, a.g+b.g, a.b+b.b) end
`;
