// ============================================================
// FluxionJS V3 — TypeScript API Generator
// Generates fluxion.d.ts: strongly-typed declarations for all
// registered engine components + static engine APIs.
// VS Code picks this up automatically for .ts user scripts.
// ============================================================

import type { EngineDef, ComponentDef, FieldDef } from '../MetaTypes';

// ── Type mapping ─────────────────────────────────────────────

function _primitiveToTsType(t: string): string {
  switch (t) {
    case 'number': case 'slider': return 'number';
    case 'boolean': return 'boolean';
    case 'string': return 'string';
    case 'vector3': case 'euler': return 'Vector3';
    case 'vector2': return 'Vector2';
    case 'color': return 'Color';
    case 'asset': return 'string | null';
    default: return 'unknown';
  }
}

function fieldToTsType(f: FieldDef): string {
  switch (f.type) {
    case 'number':
    case 'slider':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'string':
      return 'string';
    case 'vector3':
    case 'euler':
      return 'Vector3';
    case 'vector2':
      return 'Vector2';
    case 'color':
      return 'Color';
    case 'select':
      if (f.options?.length) {
        return f.options.map(o => `'${o.value}'`).join(' | ');
      }
      return 'string';
    case 'asset':
      return 'string | null';
    case 'array':
      if (f.tupleTypes?.length) {
        return `[${f.tupleTypes.map(_primitiveToTsType).join(', ')}]`;
      }
      return f.itemType ? `${_primitiveToTsType(f.itemType)}[]` : 'unknown[]';
    case 'union':
      return f.unionTypes?.length
        ? f.unionTypes.map(_primitiveToTsType).join(' | ')
        : 'unknown';
    default:
      return 'unknown';
  }
}

function emitField(f: FieldDef, indent = '    '): string {
  const tsType = fieldToTsType(f);
  const opt    = f.optional ? '?' : '';
  const rdOnly = f.readOnly ? 'readonly ' : '';
  const range  = f.min !== undefined && f.max !== undefined
    ? `range ${f.min}–${f.max}`
    : f.min !== undefined ? `min ${f.min}`
    : f.max !== undefined ? `max ${f.max}` : '';
  const parts = [f.label !== f.key ? f.label : '', range, f.description].filter(Boolean);
  const doc = parts.join(', ');
  const comment = doc ? `${indent}/** ${doc} */\n` : '';
  return `${comment}${indent}${rdOnly}${f.key}${opt}: ${tsType};`;
}

function emitComponent(c: ComponentDef): string {
  const isScript = c.category === 'Scripts';
  const deprecatedTag = c.deprecated ? ` @deprecated` : '';
  const descSuffix = c.description ? ` — ${c.description}` : '';

  if (isScript) {
    // Script classes extend FluxionBehaviour — no enabled field (that's ScriptComponent's)
    const lines: string[] = [
      `  /**${deprecatedTag} Script: ${c.displayName}${descSuffix} */`,
      `  interface ${c.typeId.replace(/^Script:/, '')} extends FluxionBehaviour {`,
    ];
    for (const f of c.fields) {
      lines.push(emitField(f));
    }
    lines.push(`  }`);
    return lines.join('\n');
  }

  const lines: string[] = [
    `  /**${deprecatedTag} [${c.category}] ${c.displayName} component${descSuffix} */`,
    `  interface ${c.typeId} {`,
    `    /** Whether this component is active */`,
    `    enabled: boolean;`,
  ];
  for (const f of c.fields) {
    lines.push(emitField(f));
  }
  lines.push(`  }`);
  return lines.join('\n');
}

// ── Static preamble — always emitted ─────────────────────────

const STATIC_PREAMBLE_HEAD = `\
// ============================================================
// FluxionJS V3 — Auto-generated Script API
// Generated by MetaSystem — do not edit manually.
// Regenerated each time the project is opened in the editor.
// ============================================================

import type * as _THREE from 'three';

declare namespace FluxionEngine {

  // ── Primitive types ────────────────────────────────────────
  interface Vector3 {
    x: number; y: number; z: number;
    set(x: number, y: number, z: number): this;
    copy(v: Vector3): this;
    add(v: Vector3): this;
    sub(v: Vector3): this;
    multiplyScalar(s: number): this;
    length(): number;
    normalize(): this;
    dot(v: Vector3): number;
    cross(v: Vector3): this;
    clone(): Vector3;
    distanceTo(v: Vector3): number;
    lerp(v: Vector3, alpha: number): this;
    applyQuaternion(q: Quaternion): this;
  }
  interface Vector2 {
    x: number; y: number;
    set(x: number, y: number): this;
    clone(): Vector2;
  }
  interface Quaternion {
    x: number; y: number; z: number; w: number;
    setFromEuler(e: Euler): this;
    setFromAxisAngle(axis: Vector3, angle: number): this;
    multiply(q: Quaternion): this;
    slerp(q: Quaternion, t: number): this;
    clone(): Quaternion;
  }
  interface Color {
    r: number; g: number; b: number;
    set(v: string | number | Color): this;
    clone(): Color;
    lerp(c: Color, alpha: number): this;
  }
  interface Euler {
    x: number; y: number; z: number; order: string;
    set(x: number, y: number, z: number): this;
    clone(): Euler;
  }

  // ── Transform ──────────────────────────────────────────────
  interface Transform {
    /** Local position */
    position: Vector3;
    /** Local Euler rotation (radians) */
    rotation: Euler;
    /** Local scale */
    scale: Vector3;
    /** World-space position — do not assign */
    readonly worldPosition: Readonly<Vector3>;
    /** World-space Euler rotation — do not assign */
    readonly worldRotation: Readonly<Euler>;
    /** World-space scale — do not assign */
    readonly worldScale: Readonly<Vector3>;
    /** Parent entity ID, or null if root */
    readonly parent: number | null;
    /** Direct child entity IDs */
    readonly children: readonly number[];
  }

  // ── Engine static APIs ─────────────────────────────────────
  interface TimeAPI {
    readonly deltaTime: number;
    readonly unscaledDeltaTime: number;
    readonly fixedDeltaTime: number;
    timeScale: number;
    readonly elapsed: number;
    readonly frameCount: number;
    readonly fps: number;
    readonly smoothFps: number;
    readonly fixedAlpha: number;
  }

  interface InputAPI {
    isKeyDown(code: string): boolean;
    isKeyPressed(code: string): boolean;
    isKeyReleased(code: string): boolean;
    isMouseDown(button?: number): boolean;
    isMousePressed(button?: number): boolean;
    isMouseReleased(button?: number): boolean;
    isPointerLocked(): boolean;
    lockPointer(): void;
    unlockPointer(): void;
    getAxis(negative: string, positive: string): number;
    getGamepadAxis(padIndex: number, axisIndex: number, deadzone?: number): number;
    isGamepadButtonDown(padIndex: number, buttonIndex: number): boolean;
    readonly mousePosition: Vector2;
    readonly mouseDelta: Vector2;
    readonly mouseWheel: number;
    readonly horizontal: number;
    readonly vertical: number;
  }

  interface RaycastHit {
    entityId: number;
    point: Vector3;
    normal: Vector3;
    distance: number;
    colliderType: string;
  }

  interface PhysicsAPI {
    /** Cast a ray and return the first hit, or null. */
    raycast(origin: Vector3, direction: Vector3, maxDistance?: number): RaycastHit | null;
    setGravity(x: number, y: number, z: number): void;
    applyForce(entityId: number, force: Vector3): void;
    applyImpulse(entityId: number, impulse: Vector3): void;
    applyTorque(entityId: number, torque: Vector3): void;
    setVelocity(entityId: number, velocity: Vector3): void;
    getVelocity(entityId: number): Vector3;
  }

  interface DebugAPI {
    log(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;
    drawLine(start: Vector3, end: Vector3, color?: Color): void;
    drawLineSphere(center: Vector3, radius: number, color?: Color, segments?: number): void;
    drawLineBox(min: Vector3, max: Vector3, color?: Color): void;
    drawCross(position: Vector3, size: number, color?: Color): void;
  }

  interface SceneAPI {
    readonly name: string;
    load(path: string): void;
  }

  interface ApplicationAPI {
    readonly fps: number;
    readonly isEditor: boolean;
    readonly platform: string;
    quit(): void;
  }

  // ── Coroutines ─────────────────────────────────────────────
  type CoroutineHandle = symbol;
  /** Yield this to wait N real seconds: \`yield { seconds: 2 }\` */
  interface WaitForSeconds { seconds: number }
  /** Yield this to wait N frames: \`yield { frames: 10 }\` */
  interface WaitForFrames { frames: number }

  // ── GameObject (entity wrapper) ────────────────────────────
  interface GameObject {
    readonly id: number;
    name: string;
    enabled: boolean;
    readonly transform: Transform;
    getComponent<K extends string>(typeId: K): (K extends keyof ComponentMap ? ComponentMap[K] : unknown) | null;
    hasComponent(typeId: string): boolean;
    addComponent<K extends string>(typeId: K): K extends keyof ComponentMap ? ComponentMap[K] : unknown;
    removeComponent(typeId: string): void;
    readonly parent: GameObject | null;
    readonly children: readonly GameObject[];
    addTag(tag: string): void;
    hasTag(tag: string): boolean;
    find(name: string): GameObject | null;
    findAll(tag: string): GameObject[];
    destroy(): void;
  }

  // ── FUI (FluxionUI) ────────────────────────────────────────
  interface FuiAPI {
    load(path: string): void;
    create(doc: unknown): void;
    setText(nodeId: string, text: string): void;
    show(): void;
    hide(): void;
    setVisible(visible: boolean): void;
    playAnimation(id: string): void;
    stopAnimation(): void;
    setScreenPosition(x: number, y: number): void;
    onButtonClick(elementId: string, callback: () => void): void;
    onAnyClick(callback: (elementId: string) => void): void;
  }
`;

// ── FluxionBehaviour class — emitted AFTER ComponentMap ──────
// ComponentMap must be declared first so the conditional types below resolve.

const STATIC_BEHAVIOUR = `\
  // ── FluxionBehaviour base class ────────────────────────────
  abstract class FluxionBehaviour {
    /**
     * Low-level ECS entity ID for this script's entity.
     * Prefer \`gameObject\` for component access, hierarchy, and queries.
     * Use \`entity\` only when calling APIs that explicitly require a raw ID
     * (e.g. \`getComponentOf\`, \`getParent\`, physics force calls).
     */
    readonly entity: number;

    /**
     * High-level wrapper around this entity — the preferred scripting API.
     * Use \`gameObject\` instead of raw entity IDs for:
     *   - component access: \`this.gameObject.getComponent('Camera')\`
     *   - hierarchy:        \`this.gameObject.parent\`, \`.children\`
     *   - scene queries:    \`this.gameObject.find('Enemy')\`
     * \`gameObject\` holds the same entity as \`this.entity\` internally.
     */
    readonly gameObject: GameObject;

    /** Shortcut to this entity's Transform component. */
    readonly transform: Transform;

    /** Engine time API. */
    protected readonly Time: TimeAPI;

    /** Input manager — keyboard, mouse, gamepad. */
    protected readonly Input: InputAPI;

    /** Physics world — raycast, forces. */
    protected readonly Physics: PhysicsAPI;

    /** Debug draw and console. */
    protected readonly Debug: DebugAPI;

    /** Scene management. */
    protected readonly Scene: SceneAPI;

    /** Application info. */
    protected readonly Application: ApplicationAPI;

    /** FluxionUI API for the FuiComponent on this entity. */
    protected readonly ui: FuiAPI;

    // ── Component access ─────────────────────────────────────
    // Prefer gameObject.getComponent() for high-level access.
    // Use getComponent() / getComponentOf() for direct ECS calls.

    /** Get a component on this entity. Equivalent to \`this.gameObject.getComponent(typeId)\`. */
    getComponent<K extends string>(typeId: K): (K extends keyof ComponentMap ? ComponentMap[K] : unknown) | null;
    /**
     * Get a component on **another** entity by its raw ECS entity ID.
     * Low-level — prefer obtaining the target's \`GameObject\` when possible.
     */
    getComponentOf<K extends string>(entityId: number, typeId: K): (K extends keyof ComponentMap ? ComponentMap[K] : unknown) | null;
    hasComponent(typeId: string): boolean;
    addComponent<K extends string>(typeId: K): K extends keyof ComponentMap ? ComponentMap[K] : unknown;
    removeComponent(typeId: string): void;

    // ── Scene queries — return raw entity IDs (low-level) ────
    // These return numbers, not GameObjects. Use the returned ID with
    // getComponentOf() or pass it to other low-level APIs.
    find(name: string): number | undefined;
    findWithTag(tag: string): number | undefined;
    findAll(tag: string): number[];
    query(...typeIds: string[]): number[];
    createEntity(name?: string): number;
    destroy(entityId?: number): void;
    getName(entityId?: number): string;
    setName(name: string, entityId?: number): void;
    getParent(entityId?: number): number | undefined;
    getChildren(entityId?: number): ReadonlySet<number>;

    // ── Tags ────────────────────────────────────────────────
    addTag(tag: string, entityId?: number): void;
    hasTag(tag: string, entityId?: number): boolean;

    // ── Events ──────────────────────────────────────────────
    on<T = unknown>(event: string, callback: (data: T) => void, priority?: number): void;
    once<T = unknown>(event: string, callback: (data: T) => void, priority?: number): void;
    emit<T = unknown>(event: string, data?: T): void;

    // ── Coroutines ──────────────────────────────────────────
    startCoroutine(gen: Generator): CoroutineHandle;
    stopCoroutine(handle: CoroutineHandle): void;

    // ── Audio ───────────────────────────────────────────────
    playSound(audioComp: AudioSourceComponent, position?: Vector3): void;

    // ── Logging ─────────────────────────────────────────────
    log(...args: unknown[]): void;
    warn(...args: unknown[]): void;
    error(...args: unknown[]): void;

    // ── Lifecycle (override in subclass) ────────────────────
    /** Called once when the script first activates. */
    start?(): void | Promise<void>;
    /** Called every frame. \`deltaTime\` is seconds since last frame. */
    update?(deltaTime: number): void;
    /** Called at fixed physics timestep. */
    fixedUpdate?(deltaTime: number): void;
    /** Called after all update() calls this frame. */
    lateUpdate?(deltaTime: number): void;
    /** Called when the entity is destroyed or the scene is cleared. */
    onDestroy?(): void;
    /** Called when this script becomes enabled. */
    onEnable?(): void;
    /** Called when this script becomes disabled. */
    onDisable?(): void;
  }
`;

// ── Generated component section ──────────────────────────────

const STATIC_SUFFIX = `
}

// ── Globals injected into every script scope ─────────────────
declare const THREE: typeof _THREE;
declare const Vec2: typeof _THREE.Vector2;
declare const Vec3: typeof _THREE.Vector3;
declare const Vec4: typeof _THREE.Vector4;
declare const Quat: typeof _THREE.Quaternion;
declare const Color: typeof _THREE.Color;
declare const Euler: typeof _THREE.Euler;
declare const Mat4: typeof _THREE.Matrix4;
declare const Mat3: typeof _THREE.Matrix3;
declare const Debug: FluxionEngine.DebugAPI;
declare const FuiBuilder: any;
declare const EntityRef: typeof import('./EntityRef').EntityRef;

declare const Mathf: {
  readonly PI: number;
  readonly TAU: number;
  readonly Deg2Rad: number;
  readonly Rad2Deg: number;
  lerp(a: number, b: number, t: number): number;
  clamp(v: number, min: number, max: number): number;
  clamp01(v: number): number;
  smoothstep(edge0: number, edge1: number, x: number): number;
  approximately(a: number, b: number): boolean;
  moveTowards(current: number, target: number, maxDelta: number): number;
  repeat(t: number, length: number): number;
  deltaAngle(a: number, b: number): number;
  pingPong(t: number, length: number): number;
  abs(x: number): number;
  ceil(x: number): number;
  floor(x: number): number;
  round(x: number): number;
  sin(x: number): number;
  cos(x: number): number;
  atan2(y: number, x: number): number;
  sqrt(x: number): number;
  sign(x: number): number;
  pow(x: number, y: number): number;
  min(...v: number[]): number;
  max(...v: number[]): number;
};

/** Base class for all FluxionJS user scripts. */
declare abstract class FluxionBehaviour extends FluxionEngine.FluxionBehaviour {}
`;

// ── Pure utility function declarations ───────────────────────
// Appended after STATIC_SUFFIX so they appear as script-scope globals.

const STATIC_UTIL_FUNCTIONS = `
// ── Pure utility functions ────────────────────────────────────
// Stateless functional alternatives to class methods.
// All functions return new values — inputs are never mutated.

// ── Constructors ──────────────────────────────────────────────
/** Create a Vector3. Shorthand for \`new Vec3(x, y, z)\`. */
declare function vec3(x: number, y: number, z: number): FluxionEngine.Vector3;
/** Create a Vector2. Shorthand for \`new Vec2(x, y)\`. */
declare function vec2(x: number, y: number): FluxionEngine.Vector2;
/** Create a Color from r/g/b components in the [0, 1] range. */
declare function color(r: number, g: number, b: number): FluxionEngine.Color;
/** Create a Color from a CSS hex string, e.g. \`"#ff8800"\`. */
declare function color_hex(hex: string): FluxionEngine.Color;

// ── Vector3 ───────────────────────────────────────────────────
/** Add two Vector3 values. */
declare function vec3_add(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3): FluxionEngine.Vector3;
/** Subtract b from a. */
declare function vec3_sub(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3): FluxionEngine.Vector3;
/** Multiply a Vector3 by a scalar. */
declare function vec3_mul(a: FluxionEngine.Vector3, s: number): FluxionEngine.Vector3;
/** Divide a Vector3 by a scalar. */
declare function vec3_div(a: FluxionEngine.Vector3, s: number): FluxionEngine.Vector3;
/** Negate a Vector3 (all components × −1). */
declare function vec3_neg(a: FluxionEngine.Vector3): FluxionEngine.Vector3;
/** Dot product of two Vector3 values. */
declare function vec3_dot(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3): number;
/** Cross product of two Vector3 values. */
declare function vec3_cross(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3): FluxionEngine.Vector3;
/** Euclidean length (magnitude) of a Vector3. */
declare function vec3_length(a: FluxionEngine.Vector3): number;
/** Squared length — avoids a sqrt; useful for distance comparisons. */
declare function vec3_length_sq(a: FluxionEngine.Vector3): number;
/** Return the unit vector of a. */
declare function vec3_normalize(a: FluxionEngine.Vector3): FluxionEngine.Vector3;
/** Linearly interpolate between a and b by t ∈ [0, 1]. */
declare function vec3_lerp(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3, t: number): FluxionEngine.Vector3;
/** Euclidean distance between two points. */
declare function vec3_distance(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3): number;
/** Squared distance — avoids a sqrt; useful for comparisons. */
declare function vec3_distance_sq(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3): number;
/** Reflect a direction vector off a surface with the given outward normal. */
declare function vec3_reflect(dir: FluxionEngine.Vector3, normal: FluxionEngine.Vector3): FluxionEngine.Vector3;
/** Project vector a onto vector b (component of a along b). */
declare function vec3_project(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3): FluxionEngine.Vector3;
/** Unsigned angle in radians between two direction vectors. */
declare function vec3_angle(a: FluxionEngine.Vector3, b: FluxionEngine.Vector3): number;

// ── Vector2 ───────────────────────────────────────────────────
/** Add two Vector2 values. */
declare function vec2_add(a: FluxionEngine.Vector2, b: FluxionEngine.Vector2): FluxionEngine.Vector2;
/** Subtract b from a. */
declare function vec2_sub(a: FluxionEngine.Vector2, b: FluxionEngine.Vector2): FluxionEngine.Vector2;
/** Multiply a Vector2 by a scalar. */
declare function vec2_mul(a: FluxionEngine.Vector2, s: number): FluxionEngine.Vector2;
/** Dot product of two Vector2 values. */
declare function vec2_dot(a: FluxionEngine.Vector2, b: FluxionEngine.Vector2): number;
/** Euclidean length (magnitude) of a Vector2. */
declare function vec2_length(a: FluxionEngine.Vector2): number;
/** Return the unit vector of a. */
declare function vec2_normalize(a: FluxionEngine.Vector2): FluxionEngine.Vector2;
/** Linearly interpolate between a and b by t ∈ [0, 1]. */
declare function vec2_lerp(a: FluxionEngine.Vector2, b: FluxionEngine.Vector2, t: number): FluxionEngine.Vector2;
/** Unsigned angle in radians between two Vector2 directions. */
declare function vec2_angle(a: FluxionEngine.Vector2, b: FluxionEngine.Vector2): number;

// ── Color ─────────────────────────────────────────────────────
/** Linearly interpolate between two Colors by t ∈ [0, 1]. */
declare function color_lerp(a: FluxionEngine.Color, b: FluxionEngine.Color, t: number): FluxionEngine.Color;
/** Scale all color components by a scalar (clamped to [0, 1]). */
declare function color_mul(c: FluxionEngine.Color, s: number): FluxionEngine.Color;
/** Add two colors component-wise (each channel clamped to [0, 1]). */
declare function color_add(a: FluxionEngine.Color, b: FluxionEngine.Color): FluxionEngine.Color;
`;

// ── Component map emitter ─────────────────────────────────────

function emitComponentMap(def: EngineDef): string {
  const lines: string[] = [
    '',
    '  // ── Component map (typeId → interface) ─────────────────',
    '  /**',
    '   * Maps every component type ID to its concrete interface.',
    '   * Enables typed component access:',
    '   *   const rb = this.getComponent(\'Rigidbody\'); // → Rigidbody | null',
    '   */',
    '  interface ComponentMap {',
  ];
  for (const c of def.components) {
    if (c.category === 'Scripts') continue;
    lines.push(`    ${JSON.stringify(c.typeId)}: ${c.typeId};`);
  }
  lines.push('  }');
  lines.push('  /** Union of all registered component type IDs */');
  lines.push('  type ComponentTypeId = keyof ComponentMap;');
  return lines.join('\n');
}

// ── Main export ──────────────────────────────────────────────

export class TypeScriptGenerator {
  static generate(def: EngineDef): string {
    const sections: string[] = [STATIC_PREAMBLE_HEAD];

    // Group components by category
    const byCategory = new Map<string, ComponentDef[]>();
    for (const c of def.components) {
      const cat = c.category;
      const arr = byCategory.get(cat) ?? [];
      arr.push(c);
      byCategory.set(cat, arr);
    }

    for (const [cat, comps] of byCategory) {
      sections.push(`\n  // ── ${cat} ` + '─'.repeat(Math.max(2, 50 - cat.length)));
      for (const c of comps) {
        sections.push(emitComponent(c));
      }
    }

    sections.push(emitComponentMap(def));
    sections.push(STATIC_BEHAVIOUR);
    sections.push(STATIC_SUFFIX);
    sections.push(STATIC_UTIL_FUNCTIONS);
    return sections.join('\n');
  }
}
