// ============================================================
// FluxionJS V3 — Particle Simulation Bridge
// Routes the per-frame particle integration step through the
// fluxion-core Rust/Wasm module when available, with a pure-JS
// fallback for browser-only environments.
//
// Flat state protocol (PARTICLE_STRIDE = 16 f32 per particle):
//   [0..2]   position  xyz
//   [3..5]   velocity  xyz
//   [6]      life      (seconds remaining)
//   [7]      maxLife
//   [8]      startSize
//   [9]      endSize
//   [10..12] startColor rgb
//   [13..15] endColor   rgb
//
// Return value from Wasm (packed Float32Array):
//   [0]           alive_count (f32)
//   [1..1+a*3]    offsets  (xyz per alive particle)
//   [1+a*3..+a]   scales   (size per alive particle)
//   [+a..+a*3]    colors   (rgb per alive particle)
//   [+a*3..+a]    opacities (life/maxLife)
//   [+a..]        updated state (a × 16, compacted)
// ============================================================

export const PARTICLE_STRIDE = 16;

// ── Wasm module singleton ─────────────────────────────────────────────────────

let _wasm: any = null;
let _loading = false;

export async function initParticleSimWasm(): Promise<void> {
  if (_wasm || _loading) return;
  _loading = true;
  try {
    // @ts-ignore — generated by wasm-pack; run `npm run build:wasm` first
    const mod = await import(/* webpackChunkName: "fluxion-core" */ '../../fluxion-core/pkg/fluxion_core.js') as any;
    if (mod.default) await mod.default();
    _wasm = mod;
    console.info('[ParticleSimBridge] fluxion-core Wasm loaded.');
  } catch (e) {
    console.error('[ParticleSimBridge] Wasm load failed — particle simulation disabled.', e);
    _wasm = null;
  }
  _loading = false;
}

export function isParticleWasmReady(): boolean {
  return _wasm !== null && typeof _wasm.simulate_particles_wasm === 'function';
}

// ── Simulation result type ────────────────────────────────────────────────────

export interface ParticleSimResult {
  alive:    number;
  offsets:  Float32Array;  // xyz * alive
  scales:   Float32Array;  // size * alive
  colors:   Float32Array;  // rgb * alive
  opacities: Float32Array; // t * alive
  state:    Float32Array;  // updated state (alive * 16), compacted
}

// ── Wasm dispatch ─────────────────────────────────────────────────────────────

/**
 * Simulate one step for `count` live particles stored in `stateIn`.
 * Uses Wasm when available, falls back to inline JS otherwise.
 *
 * @param stateIn  Float32Array of length >= count * PARTICLE_STRIDE
 * @param count    Number of live particles at entry
 * @param dt       Delta time (seconds)
 * @param gravity  Y-axis gravity (e.g. -9.81)
 */
export function simulateParticles(
  stateIn: Float32Array,
  count:   number,
  dt:      number,
  gravity: number,
): ParticleSimResult {
  return _simulateWasm(stateIn, count, dt, gravity);
}

// ── Wasm path ─────────────────────────────────────────────────────────────────

function _simulateWasm(
  stateIn: Float32Array,
  count:   number,
  dt:      number,
  gravity: number,
): ParticleSimResult {
  const packed: Float32Array = _wasm.simulate_particles_wasm(
    stateIn.subarray(0, count * PARTICLE_STRIDE),
    count,
    dt,
    gravity,
  );

  const alive = packed[0] | 0;  // f32 → int
  let off = 1;

  const offsets   = packed.subarray(off, off + alive * 3); off += alive * 3;
  const scales    = packed.subarray(off, off + alive);     off += alive;
  const colors    = packed.subarray(off, off + alive * 3); off += alive * 3;
  const opacities = packed.subarray(off, off + alive);     off += alive;
  const state     = packed.subarray(off, off + alive * PARTICLE_STRIDE);

  return { alive, offsets, scales, colors, opacities, state };
}

